// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop_Man.DB;

namespace Shop_Man.Migrations
{
    [DbContext(typeof(OrderManagementDBContext))]
    [Migration("20211228155458_AddCustomerCategory")]
    partial class AddCustomerCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop_Man.Models.CartLine", b =>
                {
                    b.Property<int>("CartLineID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderID");

                    b.Property<long?>("ProductID");

                    b.Property<int>("Quantity");

                    b.HasKey("CartLineID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartLine");
                });

            modelBuilder.Entity("Shop_Man.Models.Color", b =>
                {
                    b.Property<int>("ColorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ColorID");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("Shop_Man.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Address2");

                    b.Property<string>("MobileNo1");

                    b.Property<string>("MobileNo2");

                    b.Property<string>("Name");

                    b.Property<string>("ShopAddress");

                    b.Property<string>("Shopname");

                    b.HasKey("CompanyID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Shop_Man.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<int>("CompanyID");

                    b.Property<decimal>("CurrentBalance");

                    b.Property<int>("CustomerNo");

                    b.Property<int>("CustomerSubCategoryID");

                    b.Property<string>("CustomerSubCategoryName");

                    b.Property<string>("Disrict");

                    b.Property<DateTime>("EntryDatetime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("Isdeleted");

                    b.Property<string>("MobileNo");

                    b.Property<string>("MobileNo2");

                    b.Property<string>("Name");

                    b.Property<decimal>("OpeningBalance");

                    b.Property<decimal>("OpeningCommission");

                    b.Property<decimal>("OpeningQty");

                    b.Property<int>("UserId");

                    b.HasKey("CustomerID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CustomerSubCategoryID");

                    b.HasIndex("UserId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Shop_Man.Models.CustomerCategory", b =>
                {
                    b.Property<int>("CustomerCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerCategoryName");

                    b.HasKey("CustomerCategoryID");

                    b.ToTable("CustomerCategorys");
                });

            modelBuilder.Entity("Shop_Man.Models.CustomerSubCategory", b =>
                {
                    b.Property<int>("CustomerSubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerCategoryID");

                    b.Property<string>("CustomerSubCategoryName");

                    b.HasKey("CustomerSubCategoryID");

                    b.HasIndex("CustomerCategoryID");

                    b.ToTable("CustomerSubCategorys");
                });

            modelBuilder.Entity("Shop_Man.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<int>("CompanyID");

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("GiftWrap");

                    b.Property<string>("Line1")
                        .IsRequired();

                    b.Property<string>("Line2");

                    b.Property<string>("Line3");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Shipped");

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("Zip");

                    b.HasKey("OrderID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shop_Man.Models.PermittedController", b =>
                {
                    b.Property<int>("PermittedControllerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProjControllerID");

                    b.Property<int>("UserId");

                    b.HasKey("PermittedControllerID");

                    b.HasIndex("ProjControllerID");

                    b.HasIndex("UserId");

                    b.ToTable("PermittedControllers");
                });

            modelBuilder.Entity("Shop_Man.Models.PermittedProjAction", b =>
                {
                    b.Property<int>("PermittedProjActionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PermittedControllerID");

                    b.Property<int>("ProjActionID");

                    b.Property<int>("UserId");

                    b.HasKey("PermittedProjActionID");

                    b.HasIndex("PermittedControllerID");

                    b.HasIndex("ProjActionID");

                    b.HasIndex("UserId");

                    b.ToTable("PermittedProjAction");
                });

            modelBuilder.Entity("Shop_Man.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<int>("ColorID");

                    b.Property<int>("CompanyID");

                    b.Property<decimal>("CurrentStock");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<decimal>("OpeningStock");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("ProductImageID");

                    b.Property<int>("SizeID");

                    b.HasKey("ProductID");

                    b.HasIndex("ColorID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ProductImageID");

                    b.HasIndex("SizeID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Shop_Man.Models.ProductImage", b =>
                {
                    b.Property<int>("ProductImageID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ProductImageData")
                        .HasColumnType("image");

                    b.HasKey("ProductImageID");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("Shop_Man.Models.ProjAction", b =>
                {
                    b.Property<int>("ProjActionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionController");

                    b.Property<string>("ActionDes");

                    b.Property<string>("ActionName");

                    b.Property<int>("ProjControllerID");

                    b.HasKey("ProjActionID");

                    b.HasIndex("ProjControllerID");

                    b.ToTable("ProjAction");
                });

            modelBuilder.Entity("Shop_Man.Models.ProjController", b =>
                {
                    b.Property<int>("ProjControllerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ControllerAction");

                    b.Property<string>("ControllerDes");

                    b.Property<string>("ControllerName");

                    b.HasKey("ProjControllerID");

                    b.ToTable("ProjControllers");
                });

            modelBuilder.Entity("Shop_Man.Models.Size", b =>
                {
                    b.Property<int>("SizeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("SizeID");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("Shop_Man.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addres2");

                    b.Property<string>("Address1");

                    b.Property<int>("CompanyID");

                    b.Property<string>("ContactPerson");

                    b.Property<decimal>("CurrentBalance");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("IsEdited");

                    b.Property<int>("Isdeleted");

                    b.Property<DateTime>("LastEditedDate");

                    b.Property<string>("MobileNo1");

                    b.Property<string>("MobileNo2");

                    b.Property<string>("Name");

                    b.Property<decimal>("OpeningBalance");

                    b.Property<int>("UserId");

                    b.HasKey("SupplierId");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Shop_Man.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.Property<string>("UserRole");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shop_Man.Models.UserToCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyID");

                    b.Property<int>("IsDeleted");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserId");

                    b.ToTable("UserToCompanys");
                });

            modelBuilder.Entity("Shop_Man.Models.CartLine", b =>
                {
                    b.HasOne("Shop_Man.Models.Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderID");

                    b.HasOne("Shop_Man.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("Shop_Man.Models.Customer", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Shop_Man.Models.CustomerSubCategory", "CustomerSubCategory")
                        .WithMany()
                        .HasForeignKey("CustomerSubCategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Shop_Man.Models.User", "EntryBy")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shop_Man.Models.CustomerSubCategory", b =>
                {
                    b.HasOne("Shop_Man.Models.CustomerCategory", "CustomerCategory")
                        .WithMany("CustomerSubCategorys")
                        .HasForeignKey("CustomerCategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shop_Man.Models.Order", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shop_Man.Models.PermittedController", b =>
                {
                    b.HasOne("Shop_Man.Models.ProjController", "ProjController")
                        .WithMany()
                        .HasForeignKey("ProjControllerID");

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shop_Man.Models.PermittedProjAction", b =>
                {
                    b.HasOne("Shop_Man.Models.PermittedController")
                        .WithMany("PermittedProjActions")
                        .HasForeignKey("PermittedControllerID");

                    b.HasOne("Shop_Man.Models.ProjAction", "ProjAction")
                        .WithMany()
                        .HasForeignKey("ProjActionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shop_Man.Models.Product", b =>
                {
                    b.HasOne("Shop_Man.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Shop_Man.Models.ProductImage", "ProductImage")
                        .WithMany()
                        .HasForeignKey("ProductImageID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Shop_Man.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shop_Man.Models.ProjAction", b =>
                {
                    b.HasOne("Shop_Man.Models.ProjController")
                        .WithMany("ProjActions")
                        .HasForeignKey("ProjControllerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shop_Man.Models.Supplier", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Shop_Man.Models.User", "EntryBy")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shop_Man.Models.UserToCompany", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
