// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop_Man.DB;

namespace Shop_Man.Migrations
{
    [DbContext(typeof(OrderManagementDBContext))]
    [Migration("20220717161840_AddBuyConnInSalesDetails")]
    partial class AddBuyConnInSalesDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.CustomerNoAutoNumbering", "'CustomerNoAutoNumbering', '', '1000', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop_Man.Models.AccountType", b =>
                {
                    b.Property<int>("AccountTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Name");

                    b.HasKey("AccountTypeID");

                    b.ToTable("AccountTypes");
                });

            modelBuilder.Entity("Shop_Man.Models.Article", b =>
                {
                    b.Property<int>("ArticleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ArticleID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Shop_Man.Models.Bank", b =>
                {
                    b.Property<int>("BankID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyID");

                    b.Property<string>("Name");

                    b.Property<string>("ShortName");

                    b.HasKey("BankID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Shop_Man.Models.BankAccount", b =>
                {
                    b.Property<int>("BankAccountID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountHolderName");

                    b.Property<string>("AccountName");

                    b.Property<string>("AccountNo");

                    b.Property<string>("AccountTypeName");

                    b.Property<string>("Address");

                    b.Property<int?>("BankID");

                    b.Property<string>("BankName");

                    b.Property<int?>("CompanyID");

                    b.Property<decimal>("CurrentBalance");

                    b.Property<DateTime>("Startdate");

                    b.Property<decimal>("StartingBalance");

                    b.HasKey("BankAccountID");

                    b.HasIndex("BankID");

                    b.HasIndex("CompanyID");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("Shop_Man.Models.CartLine", b =>
                {
                    b.Property<int>("CartLineID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderID");

                    b.Property<long?>("ProductID");

                    b.Property<int>("Quantity");

                    b.HasKey("CartLineID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartLine");
                });

            modelBuilder.Entity("Shop_Man.Models.CashPayment", b =>
                {
                    b.Property<int>("CashPaymentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int?>("BankAccountID");

                    b.Property<int?>("CompanyID");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("InvoicNo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CONVERT( VARCHAR,DATEPART(YEAR,PaymentDate))+'-'+CONVERT( VARCHAR,InvoicNoSL)");

                    b.Property<int>("InvoicNoSL");

                    b.Property<string>("Note");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<int?>("PaymentMediumID");

                    b.Property<decimal>("PreviousDue");

                    b.Property<int?>("SupplierId");

                    b.Property<int?>("UserId");

                    b.HasKey("CashPaymentID");

                    b.HasIndex("BankAccountID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("PaymentMediumID");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("CashPayments");
                });

            modelBuilder.Entity("Shop_Man.Models.CashReceive", b =>
                {
                    b.Property<int>("CashReceiveID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int?>("BankAccountID");

                    b.Property<int?>("CompanyID");

                    b.Property<int?>("CustomerID");

                    b.Property<DateTime>("EntryDate");

                    b.Property<string>("InvoicNo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CONVERT( VARCHAR,DATEPART(YEAR,ReceiveDate))+'-'+CONVERT( VARCHAR,InvoicNoSL)");

                    b.Property<int>("InvoicNoSL");

                    b.Property<string>("Note");

                    b.Property<int?>("PaymentMediumID");

                    b.Property<decimal>("PreviousDue");

                    b.Property<DateTime>("ReceiveDate");

                    b.Property<int?>("UserId");

                    b.HasKey("CashReceiveID");

                    b.HasIndex("BankAccountID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PaymentMediumID");

                    b.HasIndex("UserId");

                    b.ToTable("CashReceive");
                });

            modelBuilder.Entity("Shop_Man.Models.ChequeTransaction", b =>
                {
                    b.Property<int>("ChequeTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int?>("BankAccountID");

                    b.Property<DateTime>("ChequePassDate");

                    b.Property<string>("ChequeTTNo");

                    b.Property<int?>("CompanyID");

                    b.Property<int?>("CustomerID");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("InvoicNo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CONVERT( VARCHAR,DATEPART(YEAR,TranDate))+'-'+CONVERT( VARCHAR,InvoicNoSL)");

                    b.Property<int>("InvoicNoSL");

                    b.Property<bool>("IsChequePassed");

                    b.Property<string>("LedgerName");

                    b.Property<string>("Note");

                    b.Property<int?>("PaymentMediumID");

                    b.Property<int?>("SupplierId");

                    b.Property<DateTime>("TranDate");

                    b.Property<string>("Type");

                    b.Property<int?>("UserId");

                    b.HasKey("ChequeTransactionID");

                    b.HasIndex("BankAccountID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PaymentMediumID");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("ChequeTransactions");
                });

            modelBuilder.Entity("Shop_Man.Models.Color", b =>
                {
                    b.Property<int>("ColorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ColorID");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("Shop_Man.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Address2");

                    b.Property<string>("MobileNo1");

                    b.Property<string>("MobileNo2");

                    b.Property<string>("Name");

                    b.Property<string>("ShopAddress");

                    b.Property<string>("Shopname");

                    b.HasKey("CompanyID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Shop_Man.Models.CompanyProduct", b =>
                {
                    b.Property<int>("CompanyProductID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArticleID");

                    b.Property<decimal>("BuyComm");

                    b.Property<decimal>("BuyPrice");

                    b.Property<int>("CompanyID");

                    b.Property<decimal>("CurrentStock");

                    b.Property<decimal>("OpeningStock");

                    b.Property<int?>("ProdCoCategoryID");

                    b.Property<int?>("ProdNameID");

                    b.Property<int?>("ProdTypeID");

                    b.Property<decimal>("SellComm");

                    b.Property<decimal>("SellPrice");

                    b.Property<int?>("SizeID");

                    b.Property<int?>("SupplierId");

                    b.Property<int?>("UOMID");

                    b.HasKey("CompanyProductID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ProdCoCategoryID");

                    b.HasIndex("ProdNameID");

                    b.HasIndex("ProdTypeID");

                    b.HasIndex("SizeID");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UOMID");

                    b.ToTable("CompanyProducts");
                });

            modelBuilder.Entity("Shop_Man.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<int>("CompanyID");

                    b.Property<decimal>("CurrentBalance");

                    b.Property<string>("CustomerNo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CONVERT(VARCHAR, 1000 +  CustomerID )");

                    b.Property<int>("CustomerSubCategoryID");

                    b.Property<string>("CustomerSubCategoryName");

                    b.Property<string>("Disrict");

                    b.Property<int>("DistrictID");

                    b.Property<DateTime>("EntryDatetime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("Isdeleted");

                    b.Property<string>("MobileNo");

                    b.Property<string>("MobileNo2");

                    b.Property<string>("Name");

                    b.Property<decimal>("OpeningBalance");

                    b.Property<decimal>("OpeningCommission");

                    b.Property<decimal>("OpeningQty");

                    b.Property<string>("ShopName");

                    b.Property<int>("UserId");

                    b.HasKey("CustomerID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CustomerSubCategoryID");

                    b.HasIndex("DistrictID");

                    b.HasIndex("UserId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Shop_Man.Models.CustomerCategory", b =>
                {
                    b.Property<int>("CustomerCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerCategoryName");

                    b.HasKey("CustomerCategoryID");

                    b.ToTable("CustomerCategorys");
                });

            modelBuilder.Entity("Shop_Man.Models.CustomerSubCategory", b =>
                {
                    b.Property<int>("CustomerSubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerCategoryID");

                    b.Property<string>("CustomerSubCategoryName");

                    b.HasKey("CustomerSubCategoryID");

                    b.HasIndex("CustomerCategoryID");

                    b.ToTable("CustomerSubCategorys");
                });

            modelBuilder.Entity("Shop_Man.Models.DayClose", b =>
                {
                    b.Property<int>("DayCloseID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AddLess");

                    b.Property<decimal>("Balance");

                    b.Property<decimal>("BkashReceive");

                    b.Property<decimal>("Bkashpayment");

                    b.Property<decimal>("CashPayment");

                    b.Property<decimal>("CashReceive");

                    b.Property<decimal>("ChequePayment");

                    b.Property<decimal>("ChequeReceive");

                    b.Property<int>("CompanyID");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Note");

                    b.Property<decimal>("OthersPayment");

                    b.Property<decimal>("OthersReceive");

                    b.Property<decimal>("PrevBalance");

                    b.Property<int>("SlNo");

                    b.Property<decimal>("TotalPurchase");

                    b.Property<decimal>("TotalPurchaseQty");

                    b.Property<decimal>("TotalSales");

                    b.Property<decimal>("TotalSalesQty");

                    b.Property<int>("UserId");

                    b.Property<DateTime>("dDate");

                    b.HasKey("DayCloseID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserId");

                    b.ToTable("DayCloses");
                });

            modelBuilder.Entity("Shop_Man.Models.Designation", b =>
                {
                    b.Property<int>("DesignationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyID");

                    b.Property<string>("Name");

                    b.HasKey("DesignationID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("Shop_Man.Models.District", b =>
                {
                    b.Property<int>("DistrictID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("DistrictID");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Shop_Man.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BloodGroup");

                    b.Property<int>("CompanyID");

                    b.Property<string>("CurrentAddress");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<int?>("DesignationID");

                    b.Property<string>("District");

                    b.Property<string>("Division");

                    b.Property<int>("EmployeeCode");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("FatherName");

                    b.Property<string>("GeneratedCode")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CONVERT(VARCHAR, 1000 +  EmployeeID )");

                    b.Property<string>("HouseNo");

                    b.Property<bool>("IsLedgerClose");

                    b.Property<DateTime>("JoiningDate");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("MaleFemale");

                    b.Property<string>("Mobile1");

                    b.Property<string>("Mobile2");

                    b.Property<string>("MotherName");

                    b.Property<string>("NID");

                    b.Property<string>("Name");

                    b.Property<string>("PermanentAddress");

                    b.Property<string>("Religion");

                    b.Property<string>("RoadNo");

                    b.Property<decimal>("Salary");

                    b.Property<string>("Thana");

                    b.Property<int>("UserId");

                    b.Property<string>("Village");

                    b.HasKey("EmployeeID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("DesignationID");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Shop_Man.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("AutoSLNo");

                    b.Property<int>("CompanyID");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ExpensesHeadID");

                    b.Property<string>("GeneratedAutoSLNo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CONVERT( VARCHAR,DATEPART(YEAR,TranDate))+'-'+CONVERT( VARCHAR,AutoSLNo)");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("Note");

                    b.Property<DateTime>("TranDate");

                    b.Property<string>("Type");

                    b.Property<int>("UserId");

                    b.HasKey("ExpenseID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ExpensesHeadID");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Shop_Man.Models.ExpensesHead", b =>
                {
                    b.Property<int>("ExpensesHeadID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("Name");

                    b.Property<int>("UserId");

                    b.HasKey("ExpensesHeadID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserId");

                    b.ToTable("ExpensesHeads");
                });

            modelBuilder.Entity("Shop_Man.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<int>("CompanyID");

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("GiftWrap");

                    b.Property<string>("Line1")
                        .IsRequired();

                    b.Property<string>("Line2");

                    b.Property<string>("Line3");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Shipped");

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("Zip");

                    b.HasKey("OrderID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shop_Man.Models.PaymentMedium", b =>
                {
                    b.Property<int>("PaymentMediumID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID");

                    b.Property<string>("Name");

                    b.HasKey("PaymentMediumID");

                    b.HasIndex("CompanyID");

                    b.ToTable("PaymentMediums");
                });

            modelBuilder.Entity("Shop_Man.Models.PermittedController", b =>
                {
                    b.Property<int>("PermittedControllerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProjControllerID");

                    b.Property<int>("UserId");

                    b.HasKey("PermittedControllerID");

                    b.HasIndex("ProjControllerID");

                    b.HasIndex("UserId");

                    b.ToTable("PermittedControllers");
                });

            modelBuilder.Entity("Shop_Man.Models.PermittedProjAction", b =>
                {
                    b.Property<int>("PermittedProjActionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PermittedControllerID");

                    b.Property<int>("ProjActionID");

                    b.Property<int>("UserId");

                    b.HasKey("PermittedProjActionID");

                    b.HasIndex("PermittedControllerID");

                    b.HasIndex("ProjActionID");

                    b.HasIndex("UserId");

                    b.ToTable("PermittedProjAction");
                });

            modelBuilder.Entity("Shop_Man.Models.ProdCoCategory", b =>
                {
                    b.Property<int>("ProdCoCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ProdCoCategoryID");

                    b.ToTable("ProdCoCategorys");
                });

            modelBuilder.Entity("Shop_Man.Models.ProdName", b =>
                {
                    b.Property<int>("ProdNameID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ProdNameID");

                    b.ToTable("ProdNames");
                });

            modelBuilder.Entity("Shop_Man.Models.ProdType", b =>
                {
                    b.Property<int>("ProdTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ProdTypeID");

                    b.ToTable("ProdTypes");
                });

            modelBuilder.Entity("Shop_Man.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<int>("ColorID");

                    b.Property<int>("CompanyID");

                    b.Property<decimal>("CurrentStock");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<decimal>("OpeningStock");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("ProductImageID");

                    b.Property<int>("SizeID");

                    b.HasKey("ProductID");

                    b.HasIndex("ColorID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ProductImageID");

                    b.HasIndex("SizeID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Shop_Man.Models.ProductImage", b =>
                {
                    b.Property<int>("ProductImageID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ProductImageData")
                        .HasColumnType("image");

                    b.HasKey("ProductImageID");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("Shop_Man.Models.ProjAction", b =>
                {
                    b.Property<int>("ProjActionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionController");

                    b.Property<string>("ActionDes");

                    b.Property<string>("ActionName");

                    b.Property<int>("ProjControllerID");

                    b.HasKey("ProjActionID");

                    b.HasIndex("ProjControllerID");

                    b.ToTable("ProjAction");
                });

            modelBuilder.Entity("Shop_Man.Models.ProjController", b =>
                {
                    b.Property<int>("ProjControllerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ControllerAction");

                    b.Property<string>("ControllerDes");

                    b.Property<string>("ControllerIcon");

                    b.Property<string>("ControllerName");

                    b.HasKey("ProjControllerID");

                    b.ToTable("ProjControllers");
                });

            modelBuilder.Entity("Shop_Man.Models.PurchaseDetails", b =>
                {
                    b.Property<int>("PurchaseDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArticleID");

                    b.Property<string>("ArticleName");

                    b.Property<decimal>("CommissionRate");

                    b.Property<int>("CompanyID");

                    b.Property<int>("CompanyProductID");

                    b.Property<decimal>("CurrentStockQty");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("ProdNameID");

                    b.Property<string>("ProductName");

                    b.Property<int>("PurchaseHeadID");

                    b.Property<decimal>("PurchaseQtyInPair");

                    b.Property<decimal>("PurchaseRate");

                    b.Property<int?>("SizeID");

                    b.Property<string>("SizeName");

                    b.Property<int?>("UOMID");

                    b.Property<string>("UOMName");

                    b.HasKey("PurchaseDetailsID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CompanyProductID");

                    b.HasIndex("ProdNameID");

                    b.HasIndex("PurchaseHeadID");

                    b.HasIndex("SizeID");

                    b.HasIndex("UOMID");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("Shop_Man.Models.PurchaseHead", b =>
                {
                    b.Property<int>("PurchaseHeadID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AutoPurchaseHeadNo");

                    b.Property<int>("CompanyID");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("GeneratedPurchaseHeadNo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CONVERT( VARCHAR,DATEPART(YEAR,PurchaseDate))+'-'+CONVERT( VARCHAR,AutoPurchaseHeadNo)");

                    b.Property<bool>("IsCashPurchase");

                    b.Property<string>("Note1");

                    b.Property<string>("Note2");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<string>("PurchaseHeadNo");

                    b.Property<decimal>("ReceiveAmount");

                    b.Property<int?>("SupplierId");

                    b.Property<decimal>("TotalAmount");

                    b.Property<decimal>("TotalCommission");

                    b.Property<decimal>("TotalNetAmount");

                    b.Property<decimal>("TransportCost");

                    b.Property<int>("UserId");

                    b.HasKey("PurchaseHeadID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("GeneratedPurchaseHeadNo");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("PurchaseHeads");
                });

            modelBuilder.Entity("Shop_Man.Models.SalesDetails", b =>
                {
                    b.Property<int>("SalesDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArticleID");

                    b.Property<string>("ArticleName");

                    b.Property<decimal>("BuyCommRate");

                    b.Property<decimal>("BuyRate");

                    b.Property<decimal>("CommissionRate");

                    b.Property<int>("CompanyID");

                    b.Property<int>("CompanyProductID");

                    b.Property<decimal>("CurrentStockQty");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("ProdNameID");

                    b.Property<string>("ProductName");

                    b.Property<int>("SalesHeadID");

                    b.Property<decimal>("SalesQtyInPair");

                    b.Property<decimal>("SalesRate");

                    b.Property<int?>("SizeID");

                    b.Property<string>("SizeName");

                    b.Property<int?>("UOMID");

                    b.Property<string>("UOMName");

                    b.HasKey("SalesDetailsID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CompanyProductID");

                    b.HasIndex("ProdNameID");

                    b.HasIndex("SalesHeadID");

                    b.HasIndex("SizeID");

                    b.HasIndex("UOMID");

                    b.ToTable("SalesDetailss");
                });

            modelBuilder.Entity("Shop_Man.Models.SalesHead", b =>
                {
                    b.Property<int>("SalesHeadID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccNo");

                    b.Property<int>("AutoSalesNo");

                    b.Property<string>("CheckNo");

                    b.Property<DateTime>("CheckPassDate");

                    b.Property<int>("CompanyID");

                    b.Property<int?>("CustomerID");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("GeneratedSalesNo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CONVERT( VARCHAR,DATEPART(YEAR,SalesDate))+'-'+CONVERT( VARCHAR,AutoSalesNo)");

                    b.Property<bool>("IsCashSales");

                    b.Property<string>("Note1");

                    b.Property<string>("Note2");

                    b.Property<decimal>("PackingCost");

                    b.Property<int>("PaymentMediumID");

                    b.Property<decimal>("ReceiveAmount");

                    b.Property<DateTime>("SalesDate");

                    b.Property<string>("SalesNo");

                    b.Property<decimal>("TotalAmount");

                    b.Property<decimal>("TotalCommission");

                    b.Property<decimal>("TotalNetAmount");

                    b.Property<decimal>("TransportCost");

                    b.Property<int>("UserId");

                    b.HasKey("SalesHeadID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("GeneratedSalesNo");

                    b.HasIndex("PaymentMediumID");

                    b.HasIndex("UserId");

                    b.ToTable("SalesHeads");
                });

            modelBuilder.Entity("Shop_Man.Models.Size", b =>
                {
                    b.Property<int>("SizeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("SizeID");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("Shop_Man.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addres2");

                    b.Property<string>("Address1");

                    b.Property<int>("CompanyID");

                    b.Property<string>("ContactPerson");

                    b.Property<decimal>("CurrentBalance");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("IsEdited");

                    b.Property<int>("Isdeleted");

                    b.Property<DateTime>("LastEditedDate");

                    b.Property<string>("MobileNo1");

                    b.Property<string>("MobileNo2");

                    b.Property<string>("Name");

                    b.Property<decimal>("OpeningBalance");

                    b.Property<int>("SupplierSubCategoryID");

                    b.Property<int>("UserId");

                    b.HasKey("SupplierId");

                    b.HasIndex("CompanyID");

                    b.HasIndex("SupplierSubCategoryID");

                    b.HasIndex("UserId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Shop_Man.Models.SupplierCategory", b =>
                {
                    b.Property<int>("SupplierCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SupplierCategoryID1");

                    b.Property<string>("SupplierCategoryName");

                    b.HasKey("SupplierCategoryID");

                    b.HasIndex("SupplierCategoryID1");

                    b.ToTable("SupplierCategorys");
                });

            modelBuilder.Entity("Shop_Man.Models.SupplierSubCategory", b =>
                {
                    b.Property<int>("SupplierSubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SupplierCategoryID");

                    b.Property<string>("SupplierSubCategoryName");

                    b.HasKey("SupplierSubCategoryID");

                    b.HasIndex("SupplierCategoryID");

                    b.ToTable("SupplierSubCategorys");
                });

            modelBuilder.Entity("Shop_Man.Models.UOM", b =>
                {
                    b.Property<int>("UOMID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("UOMID");

                    b.ToTable("UOMs");
                });

            modelBuilder.Entity("Shop_Man.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpId");

                    b.Property<string>("FullName");

                    b.Property<decimal>("Opbalance");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.Property<string>("UserRole");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shop_Man.Models.UserToCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyID");

                    b.Property<int>("IsDeleted");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserId");

                    b.ToTable("UserToCompanys");
                });

            modelBuilder.Entity("Shop_Man.Models.Bank", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");
                });

            modelBuilder.Entity("Shop_Man.Models.BankAccount", b =>
                {
                    b.HasOne("Shop_Man.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankID");

                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");
                });

            modelBuilder.Entity("Shop_Man.Models.CartLine", b =>
                {
                    b.HasOne("Shop_Man.Models.Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderID");

                    b.HasOne("Shop_Man.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("Shop_Man.Models.CashPayment", b =>
                {
                    b.HasOne("Shop_Man.Models.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountID");

                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");

                    b.HasOne("Shop_Man.Models.PaymentMedium", "PaymentMedium")
                        .WithMany()
                        .HasForeignKey("PaymentMediumID");

                    b.HasOne("Shop_Man.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Shop_Man.Models.CashReceive", b =>
                {
                    b.HasOne("Shop_Man.Models.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountID");

                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");

                    b.HasOne("Shop_Man.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.HasOne("Shop_Man.Models.PaymentMedium", "PaymentMedium")
                        .WithMany()
                        .HasForeignKey("PaymentMediumID");

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Shop_Man.Models.ChequeTransaction", b =>
                {
                    b.HasOne("Shop_Man.Models.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountID");

                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");

                    b.HasOne("Shop_Man.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.HasOne("Shop_Man.Models.PaymentMedium", "PaymentMedium")
                        .WithMany()
                        .HasForeignKey("PaymentMediumID");

                    b.HasOne("Shop_Man.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Shop_Man.Models.CompanyProduct", b =>
                {
                    b.HasOne("Shop_Man.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID");

                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.ProdCoCategory", "ProdCoCategory")
                        .WithMany()
                        .HasForeignKey("ProdCoCategoryID");

                    b.HasOne("Shop_Man.Models.ProdName", "ProdName")
                        .WithMany()
                        .HasForeignKey("ProdNameID");

                    b.HasOne("Shop_Man.Models.ProdType", "ProdType")
                        .WithMany()
                        .HasForeignKey("ProdTypeID");

                    b.HasOne("Shop_Man.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID");

                    b.HasOne("Shop_Man.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.HasOne("Shop_Man.Models.UOM", "UOM")
                        .WithMany()
                        .HasForeignKey("UOMID");
                });

            modelBuilder.Entity("Shop_Man.Models.Customer", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.CustomerSubCategory", "CustomerSubCategory")
                        .WithMany()
                        .HasForeignKey("CustomerSubCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.User", "EntryBy")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.CustomerSubCategory", b =>
                {
                    b.HasOne("Shop_Man.Models.CustomerCategory", "CustomerCategory")
                        .WithMany("CustomerSubCategorys")
                        .HasForeignKey("CustomerCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.DayClose", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.Designation", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");
                });

            modelBuilder.Entity("Shop_Man.Models.Employee", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationID");

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.Expense", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.ExpensesHead", "ExpensesHead")
                        .WithMany()
                        .HasForeignKey("ExpensesHeadID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.ExpensesHead", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.Order", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.PaymentMedium", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.PermittedController", b =>
                {
                    b.HasOne("Shop_Man.Models.ProjController", "ProjController")
                        .WithMany()
                        .HasForeignKey("ProjControllerID");

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.PermittedProjAction", b =>
                {
                    b.HasOne("Shop_Man.Models.PermittedController")
                        .WithMany("PermittedProjActions")
                        .HasForeignKey("PermittedControllerID");

                    b.HasOne("Shop_Man.Models.ProjAction", "ProjAction")
                        .WithMany()
                        .HasForeignKey("ProjActionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.Product", b =>
                {
                    b.HasOne("Shop_Man.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.ProductImage", "ProductImage")
                        .WithMany()
                        .HasForeignKey("ProductImageID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.ProjAction", b =>
                {
                    b.HasOne("Shop_Man.Models.ProjController")
                        .WithMany("ProjActions")
                        .HasForeignKey("ProjControllerID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.PurchaseDetails", b =>
                {
                    b.HasOne("Shop_Man.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID");

                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.CompanyProduct", "CompanyProduct")
                        .WithMany()
                        .HasForeignKey("CompanyProductID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.ProdName", "ProdName")
                        .WithMany()
                        .HasForeignKey("ProdNameID");

                    b.HasOne("Shop_Man.Models.PurchaseHead")
                        .WithMany("PurchaseDetailsList")
                        .HasForeignKey("PurchaseHeadID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID");

                    b.HasOne("Shop_Man.Models.UOM", "UOM")
                        .WithMany()
                        .HasForeignKey("UOMID");
                });

            modelBuilder.Entity("Shop_Man.Models.PurchaseHead", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.HasOne("Shop_Man.Models.Company", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.SalesDetails", b =>
                {
                    b.HasOne("Shop_Man.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID");

                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.CompanyProduct", "CompanyProduct")
                        .WithMany()
                        .HasForeignKey("CompanyProductID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.ProdName", "ProdName")
                        .WithMany()
                        .HasForeignKey("ProdNameID");

                    b.HasOne("Shop_Man.Models.SalesHead")
                        .WithMany("SalesDetailsList")
                        .HasForeignKey("SalesHeadID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID");

                    b.HasOne("Shop_Man.Models.UOM", "UOM")
                        .WithMany()
                        .HasForeignKey("UOMID");
                });

            modelBuilder.Entity("Shop_Man.Models.SalesHead", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.HasOne("Shop_Man.Models.PaymentMedium", "PaymentMedium")
                        .WithMany()
                        .HasForeignKey("PaymentMediumID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.Company", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.Supplier", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.SupplierSubCategory", "SupplierSubCategory")
                        .WithMany()
                        .HasForeignKey("SupplierSubCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shop_Man.Models.User", "EntryBy")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.SupplierCategory", b =>
                {
                    b.HasOne("Shop_Man.Models.SupplierCategory")
                        .WithMany("SupplierCategorys")
                        .HasForeignKey("SupplierCategoryID1");
                });

            modelBuilder.Entity("Shop_Man.Models.SupplierSubCategory", b =>
                {
                    b.HasOne("Shop_Man.Models.SupplierCategory", "SupplierCategory")
                        .WithMany()
                        .HasForeignKey("SupplierCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shop_Man.Models.UserToCompany", b =>
                {
                    b.HasOne("Shop_Man.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");

                    b.HasOne("Shop_Man.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
